import { StyleSheet } from 'react-native';
import { colors } from '@/src/theme/colors';

const MARGEM = 20;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    paddingHorizontal: MARGEM,
    paddingTop: 16,
  },

  segmentedControl: {
    flexDirection: 'row',
    marginHorizontal: MARGEM,
    marginVertical: 16,
    backgroundColor: '#1A1A1A',
    borderRadius: 10,
    padding: 4,
    borderWidth: 1,
    borderColor: '#2a2a2a',
  },
  segmentBtn: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 8,
  },
  segmentBtnAtivo: {
    backgroundColor: colors.primary,
  },
  segmentTxt: {
    fontFamily: 'Creato-Bold',
    color: colors.text_secondary,
    fontSize: 12,
    letterSpacing: 0.8,
  },
  segmentTxtAtivo: {
    color: colors.text,
  },

  buscaContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    marginHorizontal: MARGEM,
    marginBottom: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 10,
    borderWidth: 1,
    borderColor: '#2a2a2a',
  },
  buscaInput: {
    flex: 1,
    fontFamily: 'Creato-Regular',
    color: colors.text,
    fontSize: 14,
  },

  card: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#1A1A1A',
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#2a2a2a',
  },
  cardLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    flex: 1,
  },
  escudo: {
    width: 44,
    height: 44,
    resizeMode: 'contain',
    borderRadius: 8,
  },
  escudoPlaceholder: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: '#2a2a2a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  escudoIniciais: {
    fontFamily: 'Creato-Bold',
    color: colors.azulClaro,
    fontSize: 14,
  },
  cardNome: {
    fontFamily: 'Creato-Bold',
    color: colors.text,
    fontSize: 15,
    flexShrink: 1,
  },
  cardAno: {
    fontFamily: 'Creato-Regular',
    color: colors.text_secondary,
    fontSize: 12,
    marginTop: 2,
  },
  cardAcoes: {
    flexDirection: 'row',
    gap: 8,
  },
  btnAcao: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: colors.azulClaro + '18',
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnAcaoDanger: {
    backgroundColor: colors.vermelho + '18',
  },

  fab: {
    position: 'absolute',
    bottom: 24,
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 6,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
  },

  emptyContainer: {
    alignItems: 'center',
    paddingTop: 60,
    gap: 16,
  },
  emptyText: {
    fontFamily: 'Creato-Bold',
    color: '#333',
    fontSize: 14,
    letterSpacing: 0.5,
  },
  emptyBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#1A1A1A',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2a2a2a',
  },
  emptyBtnText: {
    fontFamily: 'Creato-Bold',
    color: colors.text,
    fontSize: 13,
  },

  skeletonCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1A1A1A',
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
    gap: 14,
  },
  skeletonEscudo: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: '#2a2a2a',
  },
  skeletonTextoContainer: {
    gap: 8,
    flex: 1,
  },
  skeletonTitulo: {
    height: 14,
    borderRadius: 6,
    backgroundColor: '#2a2a2a',
    width: '60%',
  },
  skeletonSubtitulo: {
    height: 10,
    borderRadius: 6,
    backgroundColor: '#222',
    width: '40%',
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.75)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: '#1A1A1A',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 24,
    gap: 14,
    borderWidth: 1,
    borderColor: '#2a2a2a',
    alignItems: 'center',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  modalTitulo: {
    fontFamily: 'Creato-Bold',
    color: colors.text,
    fontSize: 17,
  },
  modalSubtitulo: {
    fontFamily: 'Creato-Regular',
    color: colors.text_secondary,
    fontSize: 13,
    textAlign: 'center',
  },
  modalBotoes: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
  },
  btnNao: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: '#2a2a2a',
  },
  txtNao: {
    fontFamily: 'Creato-Bold',
    color: colors.text_secondary,
    fontSize: 13,
  },
  btnSim: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: colors.vermelho + '22',
    borderWidth: 1,
    borderColor: colors.vermelho,
  },
  txtSim: {
    fontFamily: 'Creato-Bold',
    color: colors.vermelho,
    fontSize: 13,
  },

  escudoPicker: {
    width: 90,
    height: 90,
    borderRadius: 12,
    backgroundColor: '#2a2a2a',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#3a3a3a',
    borderStyle: 'dashed',
    gap: 6,
    alignSelf: 'center',
  },
  escudoPickerImg: {
    width: 90,
    height: 90,
    borderRadius: 12,
    resizeMode: 'contain',
  },
  escudoPickerTxt: {
    fontFamily: 'Creato-Regular',
    color: colors.text_secondary,
    fontSize: 11,
  },

  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#111',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 14,
    gap: 10,
    borderWidth: 1,
    borderColor: '#2a2a2a',
    width: '100%',
  },
  input: {
    flex: 1,
    fontFamily: 'Creato-Regular',
    color: colors.text,
    fontSize: 14,
  },
  btnSalvar: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    width: '100%',
  },
  btnSalvarTxt: {
    fontFamily: 'Creato-Bold',
    color: '#FFF',
    fontSize: 14,
    letterSpacing: 0.8,
  },
});